const express = require('express');
const router = express.Router();
const { getDrugStatsByAnimal } = require('../controllers/analytics/drugfreq');
const { getMonthlyTreatments } = require('../controllers/analytics/monthly');
const { getDiseaseTrends } = require('../controllers/analytics/disease');
const { getAllFarmersForVet } = require('../controllers/farmers/allfarmer');
const { getFarmerCountForVet } = require('../controllers/farmers/countfarmerbyvet');
const getClientAnimalName = require("../controllers/farmers/getClientAnimalName");
const getClientActiveAnimalCount = require("../controllers/farmers/getClientActiveAnimalCount");
const getMonthlyTreatmentCount = require("../controllers/farmers/getClientTreatment");
const getAnimalTypeCount = require("../controllers/analytics/getAnimalTypeCount");
const getClientAnimals = require("../controllers/farmers/getClientAnimal");
const getFarmerAnimals = require("../controllers/farmer_report/getFarmerAnimals");
const getAnimalHistory = require("../controllers/farmer_report/getAnimalHistory");
const { generateAnimalReport } = require('../controllers/farmer_report/downloadReport');

router.get('/:animalId/report', generateAnimalReport);
router.get('/animal-history', getAnimalHistory);
router.get('/farmer-animals', getFarmerAnimals);
router.get('/client-animal-count', getClientAnimals);
router.get('/animal-type-count', getAnimalTypeCount);
router.get('/client-monthly-treatments', getMonthlyTreatmentCount);
router.get('/client-active-animal-count', getClientActiveAnimalCount);
router.get('/client-animals', getClientAnimalName);
router.get('/farmer-count', getFarmerCountForVet);
router.get('/farmers', getAllFarmersForVet);
router.get('/disease-trends', getDiseaseTrends);
router.get('/monthly-treatments', getMonthlyTreatments);
router.get('/drugfreq', getDrugStatsByAnimal);

module.exports = router;